### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ArgumentParser'

### ISSUE THREAD

**Issue by davidozog** [davidozog/Fast-Equilibration-Workflow#16]
When setting --prefix to the repository path (a totally reasonable thing to do), the following error occurs when running "create_chain":
```
Traceback (most recent call last):
  File "/home/user/Fast-Equilibration-Workflow/bin/create_chain", line 19, in <module>
    feqparams = feq.FEQ_Params('Create a polymer chain with the chain.f program.')
  File "/home/user/Fast-Equilibration-Workflow/bin/feq_params.py", line 7, in __init__
    parser = argparse.ArgumentParser(
AttributeError: 'module' object has no attribute 'ArgumentParser'
```
The issue is related to the existence of argparse/feq_params.py in the src directory.  Renaming the argparse dir to something else does not fix it.

**Comment by davidozog** [comment]
The current work-around is to just set --prefix to some other path, such as $HOME/usr/local.

**Comment by davidozog** [comment]
Fixed in latest master branch.
